# Generated by Django 3.0.6 on 2020-05-18 20:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GhostPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_both', models.IntegerField(default=0)),
                ('is_boast', models.BooleanField()),
                ('post', models.CharField(max_length=500)),
                ('up_votes', models.IntegerField(default=0)),
                ('down_votes', models.IntegerField(default=0)),
                ('time_post', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
